version: 2

models:
  # =======================
  # DIMENSIONS
  # =======================

  - name: dim_store
    config:
      contract:
        enforced: true
    columns:
      - name: store_key
        data_type: number
        tests: [not_null, unique]

      - name: store_id
        data_type: varchar
        tests: [not_null]

      - name: store_code
        data_type: varchar
        tests: [not_null, unique]

      - name: store_name
        data_type: varchar

      - name: city
        data_type: varchar

      - name: country
        data_type: varchar

      - name: timezone
        data_type: varchar

      - name: currency_code
        data_type: varchar

      - name: store_type
        data_type: varchar

      - name: is_active_flag
        data_type: boolean

      - name: effective_from
        data_type: timestamp_ltz

      - name: effective_to
        data_type: timestamp_ltz

      - name: is_current
        data_type: boolean

  - name: dim_customer
    config:
      contract:
        enforced: true
    columns:
      - name: customer_key
        data_type: number
        tests: [not_null, unique]

      - name: customer_id
        data_type: varchar
        tests: [not_null, unique]

      - name: loyalty_tier
        data_type: varchar

      - name: is_vip_flag
        data_type: boolean

      - name: registration_ts
        data_type: timestamp_ltz

      - name: first_purchase_ts
        data_type: timestamp_ltz

      - name: country_code
        data_type: varchar

      - name: city
        data_type: varchar

      - name: email_optin_flag
        data_type: boolean

      - name: birth_date
        data_type: date

      - name: is_active_flag
        data_type: boolean

      - name: effective_from
        data_type: timestamp_ltz

      - name: effective_to
        data_type: timestamp_ltz

      - name: is_current
        data_type: boolean

  - name: dim_product
    config:
      contract:
        enforced: true
    columns:
      - name: product_key
        data_type: number
        tests: [not_null, unique]

      - name: sku
        data_type: varchar
        tests: [not_null, unique]

      - name: product_name
        data_type: varchar

      - name: category
        data_type: varchar

      - name: brand
        data_type: varchar

      - name: vat_class
        data_type: varchar

      - name: effective_from
        data_type: timestamp_ltz

      - name: effective_to
        data_type: timestamp_ltz

      - name: is_current
        data_type: boolean

  - name: dim_channel
    config:
      contract:
        enforced: true
    columns:
      - name: channel_key
        data_type: number
        tests: [not_null, unique]

      - name: channel_code
        data_type: varchar
        tests: [not_null, unique]

      - name: channel_name
        data_type: varchar

      - name: is_digital_flag
        data_type: boolean

  - name: dim_payment
    config:
      contract:
        enforced: true
    columns:
      - name: payment_key
        data_type: number
        tests: [not_null, unique]

      - name: payment_method
        data_type: varchar
        tests: [not_null]

      - name: payment_type
        data_type: varchar

      - name: provider_name
        data_type: varchar

      - name: payment_status
        data_type: varchar

      - name: is_active_flag
        data_type: boolean

  - name: dim_currency
    config:
      contract:
        enforced: true
    columns:
      - name: currency_key
        data_type: number
        tests: [not_null, unique]

      - name: currency_code
        data_type: varchar
        tests: [not_null, unique]

      - name: currency_name
        data_type: varchar

      - name: is_active_flag
        data_type: boolean

  - name: dim_date
    config:
      contract:
        enforced: true
    columns:
      - name: date_key
        data_type: number
        tests: [not_null, unique]

      - name: full_date
        data_type: date

      - name: day_of_week
        data_type: varchar

      - name: day_name
        data_type: varchar

      - name: day_of_month
        data_type: number

      - name: week_of_year
        data_type: number

      - name: month_number
        data_type: number

      - name: month_name
        data_type: varchar

      - name: quarter
        data_type: number

      - name: year
        data_type: number

      - name: is_weekend
        data_type: boolean

      - name: month_start_date
        data_type: date

      - name: month_end_date
        data_type: date

  # =======================
  # FACTS
  # =======================
  - name: fact_order_line
    config:
      contract:
        enforced: true
    columns:
      - name: order_number # varchar
        data_type: varchar
      - name: line_number
        data_type: number(38,0)
      - name: store_key
        data_type: varchar
      - name: customer_key
        data_type: varchar
      - name: date_key
        data_type: varchar
      - name: currency_key
        data_type: varchar
      - name: channel_key
        data_type: varchar
      - name: product_key
        data_type: varchar
      - name: quantity
        data_type: number(18,3)
      - name: unit_price
        data_type: number(18,2)
      - name: discount_amount
        data_type: number(18,2)
      - name: gross_amount
        data_type: number(18,2)
      - name: vat_amount
        data_type: number(18,2)
      - name: net_amount
        data_type: number(18,2)
      - name: net_amount_aed
        data_type: number(18,2)
      - name: order_local_ts
        data_type: timestamp_ltz
      - name: load_date
        data_type: date

  - name: fact_order
    config:
      contract:
        enforced: true
    columns:
      - name: order_number
        data_type: varchar
      - name: customer_key
        data_type: varchar
      - name: store_key
        data_type: varchar
      - name: channel_key
        data_type: varchar
      - name: currency_key
        data_type: varchar
      - name: date_key
        data_type: varchar
      - name: payment_key
        data_type: varchar
      - name: order_local_ts
        data_type: timestamp_ltz
      - name: order_utc_ts
        data_type: timestamp_ltz
      - name: items_count
        data_type: number(38,0)
      - name: lines_count
        data_type: number(38,0)
      - name: order_gross_native
        data_type: number(18,2)
      - name: order_net_native
        data_type: number(18,2)
      - name: order_net_aed
        data_type: number(18,2)
      - name: order_flag_code
        data_type: varchar
      - name: final_status
        data_type: varchar
      - name: load_date
        data_type: date
