version: 2

models:
  - name: mart_monthly_orders_by_store
    columns:
      - name: month_key
        tests: [not_null]
      - name: store_code
        tests: [not_null]

  - name: mart_net_sales_by_country_monthly
    columns:
      - name: month_key
        tests: [not_null]
      - name: country_code
        tests: [not_null]

  - name: mart_orders_by_payment_method_monthly
    columns:
      - name: month_key
        tests: [not_null]
      - name: payment_method
        tests: [not_null]

  - name: mart_aov_monthly
    columns:
      - name: month_key
        tests: [not_null]

  - name: mart_refund_rate_amount_monthly
    columns:
      - name: month_key
        tests: [not_null]

  - name: mart_channel_mix_monthly
    columns:
      - name: month_key
        tests: [not_null]

  - name: mart_store_target_vs_actual_monthly
    columns:
      - name: month_key
        tests: [not_null]

  - name: mart_store_performance_index
    columns:
      - name: month_key
        tests: [not_null]

  - name: mart_active_customers_monthly
    columns:
      - name: customer_month_key
        tests: [not_null, unique]

  - name: mart_repeat_purchase_rate_monthly
    columns:
      - name: month_key
        tests: [not_null]
exposures:
  - name: bi_monthly_orders_by_store
    type: dashboard
    maturity: medium
    owner:
      name: Data Team
      email: data@gulfmart.com
    description: "R1 — Monthly orders by store dashboard"
    depends_on:
      - ref('mart_monthly_orders_by_store')

  - name: bi_net_sales_by_country
    type: dashboard
    maturity: medium
    owner:
      name: Data Team
      email: data@gulfmart.com
    description: "R2 — Net sales ex-VAT in AED by country / month"
    depends_on:
      - ref('mart_net_sales_by_country_monthly')

  - name: bi_channel_mix_monthly
    type: dashboard
    maturity: medium
    owner:
      name: Data Team
      email: data@gulfmart.com
    description: "R6 — Online vs POS channel mix over time"
    depends_on:
      - ref('mart_channel_mix_monthly')

  - name: bi_store_target_vs_actual
    type: dashboard
    maturity: medium
    owner:
      name: FP&A Team
      email: finance@gulfmart.com
    description: "S2 — Revenue vs target gap by store / month"
    depends_on:
      - ref('mart_store_target_vs_actual_monthly')

