version: 2

models:
  - name: mart_monthly_orders_by_store
    columns:
      - name: month_key
        tests: [not_null]
      - name: store_code
        tests: [not_null]

  - name: mart_net_sales_by_country_monthly
    columns:
      - name: month_key
        tests: [not_null]
      - name: country_code
        tests: [not_null]

  - name: mart_orders_by_payment_method_monthly
    columns:
      - name: month_key
        tests: [not_null]
      - name: payment_method
        tests: [not_null]

  - name: mart_aov_monthly
    columns:
      - name: month_key
        tests: [not_null]

  - name: mart_refund_rate_amount_monthly
    columns:
      - name: month_key
        tests: [not_null]

  - name: mart_channel_mix_monthly
    columns:
      - name: month_key
        tests: [not_null]

  - name: mart_store_target_vs_actual_monthly
    columns:
      - name: month_key
        tests: [not_null]

  - name: mart_store_performance_index
    columns:
      - name: month_key
        tests: [not_null]

  - name: mart_active_customers_monthly
    columns:
      - name: customer_month_key
        tests: [not_null, unique]

  - name: mart_repeat_purchase_rate_monthly
    columns:
      - name: month_key
        tests: [not_null]
exposures:
  - name: gulfmart_store_kpi_dashboard
    type: dashboard
    maturity: high
    url: "https://your-bi-tool/dashboard/gulfmart-store-kpis"  # or placeholder
    description: "Store performance dashboard using GulfMart marts."
    owner:
      name: "Data Engineering"
      email: "data@gulfmart.local"
    depends_on:
      - ref('mart_monthly_orders_by_store')
      - ref('mart_store_target_vs_actual_monthly')
      - ref('mart_store_performance_index')
