CREATE OR REPLACE STAGE GULFMART.RAW.CRM_STAGE
  STORAGE_INTEGRATION = ADLS_INT
  URL = 'azure://datafromsources.blob.core.windows.net/crm/'
  FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1);

CREATE OR REPLACE STAGE GULFMART.RAW.OMS_STAGE
  STORAGE_INTEGRATION = ADLS_INT
  URL = 'azure://datafromsources.blob.core.windows.net/oms/'
  FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1);

CREATE OR REPLACE STAGE GULFMART.RAW.PSP_STAGE
  STORAGE_INTEGRATION = ADLS_INT
  URL = 'azure://datafromsources.blob.core.windows.net/psp/'
  FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1);

CREATE OR REPLACE STAGE GULFMART.RAW.ERP_STAGE
  STORAGE_INTEGRATION = ADLS_INT
  URL = 'azure://datafromsources.blob.core.windows.net/erp/'
  FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1);

CREATE OR REPLACE STAGE GULFMART.RAW.FINANCE_STAGE
  STORAGE_INTEGRATION = ADLS_INT
  URL = 'azure://datafromsources.blob.core.windows.net/finance/'
  FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1);

CREATE OR REPLACE STAGE GULFMART.RAW.GOV_STAGE
  STORAGE_INTEGRATION = ADLS_INT
  URL = 'azure://datafromsources.blob.core.windows.net/gov/'
  FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1);

CREATE OR REPLACE STAGE GULFMART.RAW.POS_STAGE
  STORAGE_INTEGRATION = ADLS_INT
  URL = 'azure://datafromsources.blob.core.windows.net/pos/'
  FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1);

CREATE OR REPLACE STAGE GULFMART.RAW.PIM_STAGE
  STORAGE_INTEGRATION = ADLS_INT
  URL = 'azure://datafromsources.blob.core.windows.net/pim/'
  FILE_FORMAT = (TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1);
