-- CRM
CREATE OR REPLACE TABLE GULFMART.RAW.CRM_CUSTOMERS_RAW (
  "CUSTOMER_ID_NAT" VARCHAR,
  "LOYALTY_TIER" VARCHAR,
  "IS_VIP_FLAG" VARCHAR,
  "REGISTRATION_TS" VARCHAR,
  "FIRST_PURCHASE_TS" VARCHAR,
  "COUNTRY_CODE" VARCHAR,
  "CITY" VARCHAR,
  "EMAIL_OPTIN_FLAG" VARCHAR,
  "BIRTH_DATE" VARCHAR,
  "ADDRESS" VARCHAR,
  "IS_ACTIVE_FLAG" VARCHAR,
  "EFFECTIVE_FROM" VARCHAR,
  "EFFECTIVE_TO" VARCHAR
);

-- OMS (orders)
CREATE OR REPLACE TABLE GULFMART.RAW.OMS_ORDERS_RAW (
  "SOURCE_SYSTEM" VARCHAR,
  "ORDER_NUMBER" VARCHAR,
  "STORE_ID" VARCHAR,
  "CUSTOMER_ID_NAT" VARCHAR,
  "CHANNEL" VARCHAR,
  "FINAL_STATUS" VARCHAR,
  "ORDER_LOCAL_TS" VARCHAR,
  "ORDER_UTC_TS" VARCHAR,
  "ORDER_FLAG" VARCHAR,
  "INGESTION_DATE" VARCHAR
);
-- OMS (order items)
CREATE OR REPLACE TABLE GULFMART.RAW.OMS_ORDER_ITEMS_RAW (
  "SOURCE_SYSTEM" VARCHAR,
  "ORDER_NUMBER" VARCHAR,
  "LINE_NUMBER" VARCHAR,
  "STORE_ID" VARCHAR,
  "SKU" VARCHAR,
  "QUANTITY" VARCHAR,
  "UNIT_PRICE" VARCHAR,
  "DISCOUNT_AMOUNT" VARCHAR,
  "GROSS_AMOUNT" VARCHAR,
  "VAT_AMOUNT" VARCHAR,
  "NET_AMOUNT" VARCHAR,
  "COUNTRY" VARCHAR,
  "CURRENCY_CODE" VARCHAR,
  "CATEGORY" VARCHAR,
  "ORDER_LOCAL_TS" VARCHAR,
  "ORDER_UTC_TS" VARCHAR,
  "INGESTION_DATE" VARCHAR
);

-- OMS (returns)
CREATE OR REPLACE TABLE GULFMART.RAW.OMS_RETURNS_RAW (
  "SOURCE_SYSTEM" VARCHAR,
  "RETURN_ID" VARCHAR,
  "ORDER_NUMBER" VARCHAR,
  "LINE_NUMBER" VARCHAR,
  "STORE_ID" VARCHAR,
  "QUANTITY_RETURNED" VARCHAR,
  "REFUND_NET_NATIVE" VARCHAR,
  "CURRENCY_CODE" VARCHAR,
  "RETURN_REASON_CODE" VARCHAR,
  "RETURN_LOCAL_TS" VARCHAR,
  "RETURN_UTC_TS" VARCHAR,
  "INGESTION_DATE" VARCHAR
);

-- PSP (payments)
CREATE OR REPLACE TABLE GULFMART.RAW.PSP_PAYMENTS_RAW (
  "SOURCE_SYSTEM" VARCHAR,
  "PAYMENT_ID" VARCHAR,
  "ORDER_NUMBER" VARCHAR,
  "STORE_ID" VARCHAR,
  "PAYMENT_TYPE" VARCHAR,  
  "PAYMENT_STATUS" VARCHAR,
  "PAYMENT_METHOD" VARCHAR,
  "AMOUNT_NATIVE" VARCHAR,
  "FEE_NATIVE" VARCHAR,
  "CURRENCY_CODE" VARCHAR,
  "PAYMENT_LOCAL_TS" VARCHAR,
  "PAYMENT_UTC_TS" VARCHAR,
  "INGESTION_DATE" VARCHAR
);

-- PIM (products)
CREATE OR REPLACE TABLE GULFMART.RAW.PIM_PRODUCTS_RAW (
  "PRODUCT_ID" VARCHAR,
  "SKU" VARCHAR,
  "PRODUCT_NAME" VARCHAR,
  "CATEGORY" VARCHAR,
  "SUBCATEGORY" VARCHAR,
  "BRAND" VARCHAR,
  "VAT_CLASS" VARCHAR,
  "IS_ACTIVE_FLAG" VARCHAR,
  "EFFECTIVE_FROM" VARCHAR,
  "EFFECTIVE_TO" VARCHAR
);

-- POS (stores)
CREATE OR REPLACE TABLE GULFMART.RAW.POS_STORES_RAW (
  "STORE_ID" VARCHAR,
  "STORE_NAME" VARCHAR,
  "CITY" VARCHAR,
  "COUNTRY" VARCHAR,
  "CURRENCY_CODE" VARCHAR,
  "TIMEZONE" VARCHAR,
  "STORE_TYPE" VARCHAR,
  "IS_ACTIVE_FLAG" VARCHAR,
  "EFFECTIVE_FROM" VARCHAR,
  "EFFECTIVE_TO" VARCHAR
);

-- ERP (FX rates)
CREATE OR REPLACE TABLE GULFMART.RAW.ERP_FX_RATES_DAILY_RAW (
  "RATE_DATE" VARCHAR,
  "FROM_CCY" VARCHAR,
  "TO_CCY" VARCHAR,
  "RATE_TO_AED" VARCHAR,
  "SOURCE" VARCHAR
);

-- FINANCE (targets)
CREATE OR REPLACE TABLE GULFMART.RAW.FINANCE_STORE_TARGETS_MONTHLY_RAW (
  "STORE_ID" VARCHAR,
  "MONTH_KEY" VARCHAR,
  "TARGET_AMOUNT_AED" VARCHAR,
  "VARIANCE_AMOUNT_AED" VARCHAR,
  "ACHIEVED_PCT" VARCHAR,
  "INGESTION_DATE" VARCHAR
);

-- GOV (VAT policy)
CREATE OR REPLACE TABLE GULFMART.RAW.GOV_VAT_POLICY_RAW (
  "COUNTRY_CODE" VARCHAR,
  "VAT_RATE" VARCHAR,
  "ZERO_RATED_CLASS" VARCHAR,
  "EFFECTIVE_FROM" VARCHAR,
  "EFFECTIVE_TO" VARCHAR
);
