version: 2

models:
  - name: stg_customers
    description: "Lightly cleaned customers from CRM (hygiene only)."
    columns:
      - name: customer_id
        description: "Natural customer id from CRM."
        tests:
          - not_null
          - unique

      - name: loyalty_tier
        description: "Loyalty tier text from CRM."

      - name: is_vip_flag
        description: "VIP flag (boolean)."
        tests:
          - accepted_values:
              values: [true, false]

      - name: source_system
        description: "Source system code (normalized)."

      - name: registration_ts
        description: "Registration timestamp."

      - name: first_purchase_ts
        description: "First purchase timestamp."

      - name: country_code
        description: "ISO country code (uppercased)."
        tests:
          - accepted_values:
              values: ["KSA", "UAE"]

      - name: city
        description: "Customer city (initcap)."

      - name: email_optin_flag
        description: "Marketing opt-in (boolean)."
        tests:
          - accepted_values:
              values: [true, false]

      - name: birth_date
        description: "Date of birth."

      - name: ingestion_date
        description: "Landing time from RAW."
        tests:
          - not_null
  - name: stg_fx_rates_daily
    description: "Daily FROM_CCY→AED rates (one row per currency per date)."
    columns:
      - name: fx_date
        tests:
          - not_null
      - name: currency_code
        tests:
          - not_null
      - name: conversion_rate_to_aed
        tests:
          - not_null
          - dbt_utils.expression_is_true:
                expression: "conversion_rate_to_aed > 0"
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: [fx_date, currency_code]
