-- Create the main database
CREATE OR REPLACE DATABASE GULFMART;

-- Create schemas for each layer
CREATE OR REPLACE SCHEMA GULFMART.RAW;
CREATE OR REPLACE SCHEMA GULFMART.STG;
CREATE OR REPLACE SCHEMA GULFMART.CORE;
CREATE OR REPLACE SCHEMA GULFMART.MART;