-- 02_create_db_schema.sql
-- Database, schemas, and grants. Safe to rerun.

USE ROLE SYSADMIN;

-- Main database
CREATE OR REPLACE DATABASE GULFMART;

-- Schemas for each layer
CREATE OR REPLACE SCHEMA GULFMART.RAW;
CREATE OR REPLACE SCHEMA GULFMART.STG;
CREATE OR REPLACE SCHEMA GULFMART.CORE;
CREATE OR REPLACE SCHEMA GULFMART.MART;

-- Basic privileges for DBT_ROLE
GRANT USAGE ON DATABASE GULFMART TO ROLE DBT_ROLE;

GRANT USAGE ON SCHEMA GULFMART.RAW  TO ROLE DBT_ROLE;
GRANT USAGE ON SCHEMA GULFMART.STG  TO ROLE DBT_ROLE;
GRANT USAGE ON SCHEMA GULFMART.CORE TO ROLE DBT_ROLE;
GRANT USAGE ON SCHEMA GULFMART.MART TO ROLE DBT_ROLE;

-- DBT needs to READ RAW
GRANT SELECT ON ALL TABLES IN SCHEMA GULFMART.RAW  TO ROLE DBT_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA GULFMART.RAW TO ROLE DBT_ROLE;

-- DBT creates & manages objects in STG/CORE/MART
GRANT CREATE TABLE ON SCHEMA GULFMART.STG  TO ROLE DBT_ROLE;
GRANT CREATE VIEW  ON SCHEMA GULFMART.STG  TO ROLE DBT_ROLE;
GRANT CREATE TABLE ON SCHEMA GULFMART.CORE TO ROLE DBT_ROLE;
GRANT CREATE VIEW  ON SCHEMA GULFMART.CORE TO ROLE DBT_ROLE;
GRANT CREATE TABLE ON SCHEMA GULFMART.MART TO ROLE DBT_ROLE;
GRANT CREATE VIEW  ON SCHEMA GULFMART.MART TO ROLE DBT_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE
  ON ALL TABLES IN SCHEMA GULFMART.STG  TO ROLE DBT_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE
  ON FUTURE TABLES IN SCHEMA GULFMART.STG TO ROLE DBT_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE
  ON ALL TABLES IN SCHEMA GULFMART.CORE TO ROLE DBT_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE
  ON FUTURE TABLES IN SCHEMA GULFMART.CORE TO ROLE DBT_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE
  ON ALL TABLES IN SCHEMA GULFMART.MART TO ROLE DBT_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE
  ON FUTURE TABLES IN SCHEMA GULFMART.MART TO ROLE DBT_ROLE;

-- BI role: read-only mart access
GRANT USAGE ON DATABASE GULFMART       TO ROLE BI_ROLE;
GRANT USAGE ON SCHEMA   GULFMART.MART TO ROLE BI_ROLE;

GRANT SELECT ON ALL TABLES IN SCHEMA GULFMART.MART  TO ROLE BI_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA GULFMART.MART TO ROLE BI_ROLE;
