-- RAW tables are deliberately light-typed (VARCHAR). We cast/clean in STG via dbt.
-- ingestion_date defaults to CURRENT_TIMESTAMP.
-- source_system is populated during COPY using METADATA$FILENAME.
use role SYSADMIN;
use database GULFMART;
use schema RAW;

-- CRM
CREATE OR REPLACE TABLE CRM_CUSTOMERS_RAW (
  "CUSTOMER_ID_NAT"   VARCHAR,
  "LOYALTY_TIER"      VARCHAR,
  "IS_VIP_FLAG"       VARCHAR,
  "SOURCE_SYSTEM"     VARCHAR,
  "REGISTRATION_TS"   VARCHAR,
  "FIRST_PURCHASE_TS" VARCHAR,
  "COUNTRY_CODE"      VARCHAR,
  "CITY"              VARCHAR,
  "EMAIL_OPTIN_FLAG"  VARCHAR,
  "BIRTH_DATE"        VARCHAR,
  "INGESTION_DATE"    timestamp_ntz default current_timestamp()
);

-- OMS (orders)
CREATE OR REPLACE TABLE OMS_ORDERS_RAW (
  "SOURCE_SYSTEM" VARCHAR,
  "ORDER_NUMBER" VARCHAR,
  "STORE_ID" VARCHAR,
  "CUSTOMER_ID_NAT" VARCHAR,
  "CHANNEL" VARCHAR,
  "FINAL_STATUS" VARCHAR,
  "ORDER_LOCAL_TS" VARCHAR,
  "ORDER_UTC_TS" VARCHAR,
  "ORDER_FLAG" VARCHAR,
  "INGESTION_DATE" timestamp_ntz default current_timestamp()
);
-- OMS (order items)
CREATE OR REPLACE TABLE OMS_ORDER_ITEMS_RAW (
  "SOURCE_SYSTEM" VARCHAR,
  "ORDER_NUMBER" VARCHAR,
  "LINE_NUMBER" VARCHAR,
  "STORE_ID" VARCHAR,
  "SKU" VARCHAR,
  "QUANTITY" VARCHAR,
  "UNIT_PRICE" VARCHAR,
  "DISCOUNT_AMOUNT" VARCHAR,
  "GROSS_AMOUNT" VARCHAR,
  "VAT_AMOUNT" VARCHAR,
  "NET_AMOUNT" VARCHAR,
  "COUNTRY" VARCHAR,
  "CURRENCY_CODE" VARCHAR,
  "CATEGORY" VARCHAR,
  "ORDER_LOCAL_TS" VARCHAR,
  "ORDER_UTC_TS" VARCHAR,
  "INGESTION_DATE" timestamp_ntz default current_timestamp()
);

-- OMS (returns)
CREATE OR REPLACE TABLE OMS_RETURNS_RAW (
  "SOURCE_SYSTEM" VARCHAR,
  "RETURN_ID" VARCHAR,
  "ORDER_NUMBER" VARCHAR,
  "LINE_NUMBER" VARCHAR,
  "STORE_ID" VARCHAR,
  "QUANTITY_RETURNED" VARCHAR,
  "REFUND_NET_NATIVE" VARCHAR,
  "CURRENCY_CODE" VARCHAR,
  "RETURN_REASON_CODE" VARCHAR,
  "RETURN_LOCAL_TS" VARCHAR,
  "RETURN_UTC_TS" VARCHAR,
  "INGESTION_DATE" timestamp_ntz default current_timestamp()
);

-- PSP (payments)
CREATE OR REPLACE TABLE PSP_PAYMENTS_RAW (
  "SOURCE_SYSTEM" VARCHAR,
  "PAYMENT_ID" VARCHAR,
  "ORDER_NUMBER" VARCHAR,
  "STORE_ID" VARCHAR,
  "PAYMENT_TYPE" VARCHAR,  
  "PAYMENT_STATUS" VARCHAR,
  "PAYMENT_METHOD" VARCHAR,
  "AMOUNT_NATIVE" VARCHAR,
  "FEE_NATIVE" VARCHAR,
  "CURRENCY_CODE" VARCHAR,
  "PAYMENT_LOCAL_TS" VARCHAR,
  "PAYMENT_UTC_TS" VARCHAR,
  "INGESTION_DATE" timestamp_ntz default current_timestamp()
);

-- PIM (products)
CREATE OR REPLACE TABLE PIM_PRODUCTS_RAW (
  "SKU" VARCHAR,
  "PRODUCT_NAME" VARCHAR,
  "CATEGORY" VARCHAR,
  "BRAND" VARCHAR,
  "VAT_CLASS" VARCHAR,
  "SOURCE_SYSTEM" VARCHAR,
  "INGESTION_DATE" timestamp_ntz default current_timestamp()
);

-- POS (stores)
CREATE OR REPLACE TABLE POS_STORES_RAW (
  "STORE_ID" VARCHAR,
  "STORE_CODE" VARCHAR,
  "STORE_NAME" VARCHAR,
  "CITY" VARCHAR,
  "COUNTRY" VARCHAR,
  "CURRENCY_CODE" VARCHAR,
  "TIMEZONE" VARCHAR,
  "STORE_TYPE" VARCHAR,
  "OPEN_DATE" VARCHAR,
  "SOURCE_SYSTEM" VARCHAR,
  "INGESTION_DATE" timestamp_ntz default current_timestamp()
);

-- ERP (FX rates)
CREATE OR REPLACE TABLE ERP_FX_RATES_DAILY_RAW (
  "FX_DATE" VARCHAR,
  "FROM_CCY" VARCHAR,
  "TO_CCY" VARCHAR,
  "RATE_TO_AED" VARCHAR,
  "SOURCE_SYSTEM" VARCHAR,
  "INGESTION_DATE" timestamp_ntz default current_timestamp()
);

-- FINANCE (targets)
CREATE OR REPLACE TABLE FINANCE_STORE_TARGETS_MONTHLY_RAW (
  "SOURCE_SYSTEM" VARCHAR,
  "STORE_ID" VARCHAR,
  "TARGET_MONTH" VARCHAR,
  "TARGET_AMOUNT_AED" VARCHAR,
  "INGESTION_DATE" timestamp_ntz default current_timestamp()
);

-- GOV (VAT policy)
CREATE OR REPLACE TABLE GOV_VAT_POLICY_RAW (
  "COUNTRY_CODE" VARCHAR,
  "VAT_RATE" VARCHAR,
  "effective_from" VARCHAR,
  "SOURCE_SYSTEM" VARCHAR,
  "INGESTION_DATE" timestamp_ntz default current_timestamp()
);
