use role SYSADMIN;
use warehouse WH_INGEST;
use database GULFMART;
use schema RAW;

-- Customers (CRM)
COPY INTO GULFMART.RAW.CRM_CUSTOMERS_RAW
FROM @GULFMART.RAW.CRM_STAGE
PATTERN='.*crm_customers_.*\\.csv'
FILE_FORMAT=(TYPE=CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1)
ON_ERROR='CONTINUE';

-- OMS
COPY INTO GULFMART.RAW.OMS_ORDERS_RAW
FROM @GULFMART.RAW.OMS_STAGE/orders/
PATTERN='.*oms_orders_.*\\.csv'
FILE_FORMAT=(TYPE=CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1)
ON_ERROR='CONTINUE';

COPY INTO GULFMART.RAW.OMS_ORDER_ITEMS_RAW
FROM @GULFMART.RAW.OMS_STAGE/order_items/
PATTERN='.*oms_order_items_.*\\.csv'
FILE_FORMAT=(TYPE=CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1)
ON_ERROR='CONTINUE';

COPY INTO GULFMART.RAW.OMS_RETURNS_RAW
FROM @GULFMART.RAW.OMS_STAGE/returns/
PATTERN='.*oms_returns_.*\\.csv'
FILE_FORMAT=(TYPE=CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1)
ON_ERROR='CONTINUE';

-- PSP (payments)
COPY INTO GULFMART.RAW.PSP_PAYMENTS_RAW
FROM @GULFMART.RAW.PSP_STAGE/payments/2025/
PATTERN='.*psp_payments_.*\.csv'
FILE_FORMAT=(TYPE=CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1)
ON_ERROR='CONTINUE';

-- PIM, POS (single files)
COPY INTO GULFMART.RAW.PIM_PRODUCTS_RAW
FROM @GULFMART.RAW.PIM_STAGE
PATTERN='.*pim_products\\.csv'
FILE_FORMAT=(TYPE=CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1)
ON_ERROR='CONTINUE';

COPY INTO GULFMART.RAW.POS_STORES_RAW
FROM @GULFMART.RAW.POS_STAGE
PATTERN='.*pos_stores\\.csv'
FILE_FORMAT=(TYPE=CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1)
ON_ERROR='CONTINUE';

-- ERP FX (recursively under 2025/08,09,10…)
COPY INTO GULFMART.RAW.ERP_FX_RATES_DAILY_RAW
FROM @GULFMART.RAW.ERP_STAGE/fx_rates_daily/2025/
PATTERN='.*fx_rates_daily_.*\\.csv'
FILE_FORMAT=(TYPE=CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1)
ON_ERROR='CONTINUE';

-- FINANCE
COPY INTO GULFMART.RAW.FINANCE_STORE_TARGETS_MONTHLY_RAW
FROM @GULFMART.RAW.FINANCE_STAGE/store_targets_monthly/2025/
PATTERN='.*store_targets_monthly_.*\\.csv'
FILE_FORMAT=(TYPE=CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1)
ON_ERROR='CONTINUE';

-- GOV
COPY INTO GULFMART.RAW.GOV_VAT_POLICY_RAW
FROM @GULFMART.RAW.GOV_STAGE
PATTERN='.*gov_vat_policy\\.csv'
FILE_FORMAT=(TYPE=CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1)
ON_ERROR='CONTINUE';
